import re
import sys
import os

# Ensure backend/ is on path when this module is imported directly
_HERE = os.path.dirname(os.path.abspath(__file__))
_BACKEND = os.path.dirname(_HERE)
if _BACKEND not in sys.path:
    sys.path.insert(0, _BACKEND)

from chitti.memory import initialize_state, add_idea, state_to_dict
from chitti.scorer import score_all_ideas, vote_best_ideas, choose_best_idea
from swarm_engine.api import execute_swarm_sync


class ChittiOrchestrator:
    def __init__(self, agent_count: int = 5):
        self.state = None
        self.agent_count = agent_count

    def initialize(self, problem: str):
        self.state = initialize_state(problem)
        return state_to_dict(self.state)

    def deduplicate_ideas(self):
        if self.state is None:
            return
        seen = set()
        unique = []
        for idea in self.state.ideas:
            norm = idea.content.strip().lower()
            if norm not in seen:
                seen.add(norm)
                unique.append(idea)
        self.state.ideas = unique

    def ingest_swarm_result(self, result_dict: dict):
        if self.state is None:
            self.initialize(result_dict["problem"])

        self.state.iteration = result_dict.get("iterations_run", self.state.iteration)

        for idea in result_dict.get("all_ideas", []):
            add_idea(
                state=self.state,
                content=idea.get("text", idea.get("content", "")),
                agent_name=f"swarm_agent_{idea.get('agent_id', 'x')}",
                iteration=idea.get("iteration", self.state.iteration),
                parent_ids=[],
                action_type="swarm_generated",
                reason=f"Generated by {idea.get('agent_style', 'unknown')} agent",
            )

        self.deduplicate_ideas()

        return {
            "final_output": result_dict.get("final_output", ""),
            "top_ideas":    result_dict.get("top_ideas", []),
            "agent_summary": result_dict.get("agent_summary", []),
            "state":        state_to_dict(self.state),
        }

    def run_real_swarm(self, num_iterations: int = 3):
        if self.state is None:
            raise ValueError("Chitti session not initialised — call initialize() first.")

        result = execute_swarm_sync(
            problem=self.state.problem,
            num_agents=self.agent_count,
            num_iterations=num_iterations,
            send_to_mcp=False,
        )

        integrated = self.ingest_swarm_result(result.to_dict())

        score_all_ideas(self.state)
        vote_best_ideas(self.state)
        best = choose_best_idea(self.state)

        return {
            "best_idea":     best.content if best else None,
            "final_output":  result.final_output,
            "top_ideas":     integrated["top_ideas"],
            "agent_summary": integrated["agent_summary"],
            "state":         state_to_dict(self.state),
        }

    def score_and_vote(self):
        if self.state is None:
            raise ValueError("Chitti session not initialised.")
        score_all_ideas(self.state)
        vote_best_ideas(self.state)
        best = choose_best_idea(self.state)
        return {
            "best_idea": best.content if best else None,
            "state":     state_to_dict(self.state),
        }

    def run_full_process(self, iterations: int = 3):
        return self.run_real_swarm(num_iterations=iterations)

    def get_state(self):
        if self.state is None:
            raise ValueError("Chitti session not initialised.")
        return state_to_dict(self.state)
